make julialauncher have saner error messages for channels and versions
JuliaLang/juliaup pull request #767
Opened 2023-12-10 08:57 UTC by uncomfyhalomacro

closes #766

2023-12-15 14:44 UTC, uncomfyhalomacro commented
\cc @davidanthoff ready for review. if youre free :D

2024-01-04 10:19 UTC, fingolfin commented on tests/channel_selection.rs
> +        .stderr("ERROR: Invalid Juliaup channel `1.8.6`. Please run `juliaup list` to check a valid channel or version\n");
This reads a bit weird to me: "to check a valid channel or version".

Maybe "to find a valid channel or version" or "to get a list of valid channels and versions" ?

2024-01-04 10:50 UTC, uncomfyhalomacro commented
very late to you and contributors but happy new year! 🎉

@fingolfin thanks for the code review. I applied your suggestions. 🫂

2024-01-11 22:27 UTC, davidanthoff requested changes
Nice! Just a few small change requests.

2024-01-11 22:27 UTC, davidanthoff commented on src/bin/julialauncher.rs
> +        load_versions_db(&paths).with_context(|| "command failed to load versions db.")?;
I don't think we need to load it again, the function has an argument `versions_db` that can be used?

2024-01-11 22:27 UTC, davidanthoff commented on src/bin/julialauncher.rs
> +                    } else if versiondb_data.available_versions.contains_key(channel) {
I don't think we need to check in the `availabe_versions`, users can't access those versions in any, I think just looking at `available_channels` is enough. Same applies to the same `if` blocks below.

2024-01-12 03:39 UTC, davidanthoff commented
Ok, one (very!) minor last change request: could you add a period at the end of each of the error messages? That is the convention I have used throughout the project.

2024-01-12 19:15 UTC, davidanthoff approved these changes
Awesome, thanks!

2024-01-12 19:15 UTC, merged