Consider Nightly channels when checking for avaliable_channels
JuliaLang/juliaup pull request #848
Opened 2024-02-26 19:50 UTC by christiangnrd

Closes #820 but not #995.

2024-07-16 18:51 UTC, christiangnrd commented
This is ready for review.

2024-08-21 01:10 UTC, davidanthoff requested changes
Nice!

I just have some change requests in how errors are handled. 1) we should use `?` more, and 2) always bubble errors up, so that if something goes wrong that everything fails and we get an error report :)

2024-08-21 01:10 UTC, davidanthoff commented on src/operations.rs
> +    let archs: Result<Vec<String>> = compatible_archs();
I think if you just terminate this line with a `?` then you can drop the whole `if` `else` construction later in the function.

2024-08-21 01:10 UTC, davidanthoff commented on src/operations.rs
> +pub fn is_valid_channel(versions_db: &JuliaupVersionDB, channel: &String) -> bool {
Return type should also be a `Result`, right?

2024-08-21 01:10 UTC, davidanthoff commented on src/operations.rs
> +    let nightly_chans = compatible_nightly_channels();
And then terminate with `?`

2024-08-21 02:00 UTC, christiangnrd commented
Thanks for the review! I don't have much Rust experience so this is very helpful.

2024-10-06 01:18 UTC, davidanthoff approved these changes

2024-10-06 18:04 UTC, merged